general {
    hide_cursor = true
}

background {
    monitor =
    color = rgba(18, 20, 29, 1.0)
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(197, 202, 221, 1.0)
    font_size = 90
    font_family = JetBrainsMono Nerd Font
    halign = center
    valign = center
    position = 0, 150
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date +"%A, %d %B")"
    color = rgba(122, 130, 150, 1.0)
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    halign = center
    valign = center
    position = 0, 60
}

input-field {
    size = 300, 50
    halign = center
    valign = center
    position = 0, -80

    outline_thickness = 2
    dots_size = 0.3
    dots_spacing = 0.3
    placeholder_text = <span foreground="##7a8296">Enter password...</span>

    outer_color = rgba(142, 163, 201, 1.0)
    inner_color = rgba(36, 40, 55, 1.0)
    font_color = rgba(197, 202, 221, 1.0)

    fade_on_empty = false
    check_color = rgba(232, 131, 136, 1.0)
    fail_color = rgba(232, 131, 136, 1.0)
}
